# App
spring.application.name=flowdesk
server.port=8080

# Logging
logging.level.com.areswayne.flowdesk=DEBUG

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/flowdesk_db
spring.datasource.username=postgres
spring.datasource.password=*Spv3BETA*
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Flyway (desactivado hasta definir entidades y migraciones)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=5

# JWT
app.jwt.secret=flowdesk-super-secret-key-must-be-at-least-32-characters-long
app.jwt.expiration-ms=86400000
